version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:2049

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "2049:2049"
      - "2050:2050"
    volumes:
      - ./server:/app
      - /app/node_modules 